//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class empreassist
    {
        public int ID { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string MName { get; set; }
        public string Gender { get; set; }
        public string MothersMaiden { get; set; }
        public string FathersName { get; set; }
        public string ContactNumber { get; set; }
        public string SSSNumber { get; set; }
        public string PhilhealthNumber { get; set; }
        public string PagibigNumber { get; set; }
        public string TinNumber { get; set; }
        public string WithholdingTax { get; set; }
        public string PresentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string NameEmergancyContactPerson { get; set; }
        public string ContactEmgerncyPerson { get; set; }
    }
}
